DROP TABLE CALL_LOGS IF EXISTS;

CREATE TABLE CALL_LOGS
(
  RPT_DATE DATE
, CALL_TIME TIME
, SOURCE DECIMAL(20, 0)
, DESTINATION DECIMAL(20, 0)
, HH DECIMAL(2, 0)
, MM DECIMAL(2, 0)
, SS DECIMAL(2, 0)
)