spring:
  datasource:
    initialize: false
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:

logging:
  level:
    root: INFO
    com.aiglr.alip: INFO
    org.springframework: ERROR
    org.springframework.batch: INFO

file:
  location:
    input: /Users/jongtenerife/git/call-report-service/src/main/resources/input-call_20170726.csv
    output: ../output/output.csv
