spring:
  datasource:
    initialize: false
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:

mode: monitor

logging:
  level:
    root: INFO
    com.aiglr.alip: INFO
    org.springframework: ERROR
    org.springframework.batch: INFO

file:
  location:
    input: src/main/resources/input-call_20170726.csv
    output-monitor: ../output/output_monitor.csv
    output-cdr: ../output/output_cdr.csv
