spring:
  datasource:
    initialize: false
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:

logging:
  level:
    root: INFO
    com.aiglr.alip: INFO
    org.springframework: ERROR

file:
  location:
    input:
    output: ../output/output.csv
